config/routes.rb
Rails.application.routes.draw do

   root 'stoks#index'

      devise_for :users, controllers: { sessions: 'users/sessions' }
      resources :roles, only: [:index, :new, :create, :destroy]
      resources :activities
      resources :stoks
      resources :kategoris
      resources :orders, only: [:index, :show, :destroy]
      resource :cart, only: [:show]
      resources :order_items, only: [:index, :create, :update, :destroy]
      resources :clients
      resources :troubels, except: [:show]
      resources :services
      resources :kategoris do
         resources :stoks
      end

      get 'check_outs' => 'order_items#final_order', as: :check_out_route
      get 'set_nil/:id' => 'stoks#set_nil', as: :set_nil

end

app/models/service.rb
class Service < ActiveRecord::Base
   belongs_to :client
   belongs_to :troubel
   validates :code, :client_id, :troubel_id, presence: true
   before_save :generate_code

   #method untuk menghitung total biaya servis
   def service_price
      troubel.price if troubel.valid?
   end

   def total
      self[:total] = service_price
   end
   #method untuk print line
   def line
      return "=" * 121
   end

   def generate_code
      self[:code] = "#{id}#{SecureRandom.urlsafe_base64(3)}"
   end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
     respond_to do |format|
        format.html
        format.json
        format.pdf { render template: 'services/nota', pdf: 'nota' }
     end

  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Servis berhasil di buat' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Servis berhasil di perbarui' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Servis berhasil di hapus' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.fetch(:service).permit(:code, :sub_total, :total, :client_id, :troubel_id)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<div class="container">
   <div class="row">
      <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
         <h1>Form Servis</h1>
         <div class="panel panel-default">
         <!-- Default panel contents -->
            <div class="panel-body">

               <div class="col-md-9 col-sm-9">

                  <%= form_for(@service) do |s| %>
                  <fieldset disabled>
                     <div class="form-group">
                        <%= s.label :Kode_Servis, class: "control-label"%>
                        <%= s.text_field :generate_code, autofocus: true, class: "form-control", id: "disabledTextInput"  %>
                     </div>
                  </fieldset>
                  <div class="form-group">
                     <%= s.label :Jenis_Permasalahan, class: "control-label"%>
                     <%= s.collection_select 'troubel_id', Troubel.all, :id, :name, {prompt: "Silahkan pilih permasalahan"}, {class: "form-control"} %>
                  </div>
                  <div class="form-group">
                     <%= s.label :Pelanggan, class: "control-label"%>
                     <%= s.collection_select 'client_id', Client.all, :id, :first_name, {prompt: "Silahkan pilih pelanggan"}, {class: "form-control"} %>
                  </div>
                     <%= s.submit "Simpan", class: "btn btn-default btn-lg" %>
                  <% end %>
               </div>
            </div>
         </div>
      </div><!-- col-md-12 -->
   </div>
</div>

app/views/services/edit.html.erb
<%= render 'form' %>

app/views/services/index.html.erb
<div class="container">
   <div class="row">
      <div class="col-md-12 col-sm-12">
         <h1>Daftar Servis</h1>
         <div class="table-responsive">
         <table class="table table-bordered">
           <thead>
              <tr>
                 <th>
                    <%= link_to new_service_path, class: "btn btn-default" do %>
                    <i class="glyphicon glyphicon-pencil"></i> Tambahan Servis
                    <% end %>
                 </th>
              </tr>
             <tr>
               <th>Kode Servis</th>
               <th>Nama Pelanggan</th>
               <th>Jenis Servis</th>
               <th colspan="3"></th>
             </tr>
           </thead>

           <tbody>
             <% @services.each do |s| %>
               <tr>
                  <td><%= s.code %></td>
                  <td><%= s.client.first_name %> <%= s.client.last_name %></td>
                  <td><%= s.troubel.name %></td>
                  <td>
                     <%= link_to service_path(s), class: "btn btn-default" do %>
                     <i class="glyphicon glyphicon-eye-open"></i>  Lihat Nota
                    <% end %>
                  </td>
                  <td>
                     <%= link_to edit_service_path(s), class: "btn btn-default" do %>
                     <i class="glyphicon glyphicon-cog"></i> Ubah
                    <% end %>
                  </td>
                  <td>
                     <%= button_to service_path(s), method: :delete, data: { confirm: 'Apakah anda yakin ingin menghapus servis ini?' }, class: "btn btn-danger" do %>
                     <i class="glyphicon glyphicon-trash"></i> Hapus
                    <% end %>
                  </td>
               </tr>
             <% end %>
           </tbody>
         </table>
         </div>
      </div>
   </div>
</div>

app/views/services/new.html.erb
<%= render 'form' %>

app/views/services/nota.pdf.erb
<div class="container">
   <div class="row">
      <div class="col-md-12 col-sm-12">
         <table class="table table-borderd">
            <thead>
               <tr style="text-align: center;">
                  <th colspan="3">
                     <h1><b> AB COMPUTER </b></h1>
                     <h4>
                        <span class="glyphicon glyphicon-phone-alt"></span> 0858 8371 8464<br/>
                        <span class="glyphicon glyphicon-envelope"></span> musaabdillahm9@gmail.com <br/>
                        <span class="glyphicon glyphicon-home"></span> Kradenan Gang 5 No 495 Pekalongan
                     </h4>
                     <p><%= @service.line %></p>
                  </th>
               </tr>
            </thead>
            <tbody>
               <tr>
                  <td> Kode Servis</td>
                  <td> : </td>
                  <td><%= @service.code %></td>
               </tr>
               <tr>
                  <td>Nama Pelanggan</td>
                  <td> : </td>
                  <td><%= @service.client.first_name %> <%= @service.client.last_name %></td>
               </tr>
               <tr>
                  <td>No Handphone</td>
                  <td> : </td>
                  <td><%= @service.client.phone_number %></td>
               </tr>
               <tr>
                  <td>Jenis Servis</td>
                  <td> : </td>
                  <td><%= @service.troubel.name %></td>
               </tr>
               <tr>
                  <td><h3 style="font-weight: bold;"> Total Biaya </h3></td>
                  <td><h3 style="font-weight: bold;"> : </h3></td>
                  <td><h3 style="font-weight: bold;"> Rp <%= number_with_delimiter(@service.troubel.price, delimiter: '.') %> </h3></td>
               </tr>
            </tbody>
         </table>
      </div>
   </div>
</div>

app/views/services/show.html.erb
<div class="container">
   <div class="row">
      <div class="col-md-12 col-sm-12">
         <table class="table table-borderd">
            <thead>
               <tr style="text-align: center;">
                  <th colspan="3">
                     <h1><b> AB COMPUTER </b></h1>
                     <h4>
                         <span class="glyphicon glyphicon-phone-alt"></span> 0858 8371 8464 <br/>
                         <span class="glyphicon glyphicon-envelope"></span> musaabdillahm9@gmail.com <br/>
                        <span class="glyphicon glyphicon-home"></span> Kradenan Gang 5 No 495 Pekalongan
                     </h4>
                     <p><%= @service.line %></p>
                  </th>
               </tr>
            </thead>
            <tbody>
               <tr>
                  <td> Kode Servis</td>
                  <td> : </td>
                  <td><%= @service.code %></td>
               </tr>
               <tr>
                  <td>Nama Pelanggan</td>
                  <td> : </td>
                  <td><%= @service.client.first_name %> <%= @service.client.last_name %></td>
               </tr>
               <tr>
                  <td>No Handphone</td>
                  <td> : </td>
                  <td><%= @service.client.phone_number %></td>
               </tr>
               <tr>
                  <td>Jenis Servis</td>
                  <td> : </td>
                  <td><%= @service.troubel.name %></td>
               </tr>
               <tr>
                  <td><h3 style="font-weight: bold;"> Total Biaya </h3></td>
                  <td><h3 style="font-weight: bold;"> : </h3></td>
                  <td><h3 style="font-weight: bold;"> Rp <%= number_with_delimiter(@service.troubel.price, delimiter: '.') %> </h3></td>
               </tr>
            </tbody>
            <tfoot>
               <tr>
                  <td colspan="3" class="text-right">
                     <%= link_to service_path(@service, format: :pdf), class: "btn btn-default" do %>
                     <i class="glyphicon glyphicon-print"></i> Cetak
                     <% end %>
                  </td>
               </tr>
            </tfoot>
         </table>
      </div>
   </div>
</div>

app/views/services/show.pdf.erb
<div class="container">
   <div class="row">
      <div class="col-md-12 col-sm-12">
         <table class="table table-borderd">
            <thead>
               <tr style="text-align: center;">
                  <th colspan="3">
                     <h1><b> AB COMPUTER </b></h1>
                     <h4>
                         <span class="glyphicon glyphicon-phone-alt"></span> 0858 8371 8464<br/>
                         <span class="glyphicon glyphicon-envelope"></span> musaabdillahm9@gmail.com <br/>
                        <span class="glyphicon glyphicon-home"></span> Kradenan Gang 5 No 495 Pekalongan
                     </h4>
                     <p><%= @service.line %></p>
                  </th>
               </tr>
            </thead>
            <tbody>
               <tr>
                  <td> Kode Servis</td>
                  <td> : </td>
                  <td><%= @service.code %></td>
               </tr>
               <tr>
                  <td>Nama Pelanggan</td>
                  <td> : </td>
                  <td><%= @service.client.first_name %> <%= @service.client.last_name %></td>
               </tr>
               <tr>
                  <td>No Handphone</td>
                  <td> : </td>
                  <td><%= @service.client.phone_number %></td>
               </tr>
               <tr>
                  <td>Jenis Servis</td>
                  <td> : </td>
                  <td><%= @service.troubel.name %></td>
               </tr>
               <tr>
                  <td><h3 style="font-weight: bold;"> Total Biaya </h3></td>
                  <td><h3 style="font-weight: bold;"> : </h3></td>
                  <td><h3 style="font-weight: bold;"> Rp <%= number_with_delimiter(@service.troubel.price) %> </h3></td>
               </tr>
            </tbody>
         </table>
      </div>
   </div>
</div>