config/routes.rb
Rails.application.routes.draw do

   root 'stoks#index'

      devise_for :users, controllers: { sessions: 'users/sessions' }
      resources :roles, only: [:index, :new, :create, :destroy]
      resources :activities
      resources :stoks
      resources :kategoris
      resources :orders, only: [:index, :show, :destroy]
      resource :cart, only: [:show]
      resources :order_items, only: [:index, :create, :update, :destroy]
      resources :clients
      resources :troubels, except: [:show]
      resources :services
      resources :kategoris do
         resources :stoks
      end

      get 'check_outs' => 'order_items#final_order', as: :check_out_route
      get 'set_nil/:id' => 'stoks#set_nil', as: :set_nil

end

app/models/troubel.rb
class Troubel < ActiveRecord::Base
   has_many :services
   has_many :clients, through: :services
   validates :name, :grade, :price, presence: true
end

app/controllers/troubels_controller.rb
class TroubelsController < ApplicationController
  before_action :set_troubel, only: [:show, :edit, :update, :destroy]

  # GET /troubels
  # GET /troubels.json
  def index
    @troubels = Troubel.all
  end

  # GET /troubels/new
  def new
    @troubel = Troubel.new
  end

  # GET /troubels/1/edit
  def edit
  end

  # POST /troubels
  # POST /troubels.json
  def create
    @troubel = Troubel.new(troubel_params)

    respond_to do |format|
      if @troubel.save
        format.html { redirect_to troubels_path, notice: 'Permasalahan berhasil di simpan' }
        format.json { render :show, status: :created, location: @troubel }
      else
        format.html { render :new }
        format.json { render json: @troubel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /troubels/1
  # PATCH/PUT /troubels/1.json
  def update
    respond_to do |format|
      if @troubel.update(troubel_params)
        format.html { redirect_to @troubel, notice: 'Permasalahan berhasil di perbarui' }
        format.json { render :show, status: :ok, location: @troubel }
      else
        format.html { render :edit }
        format.json { render json: @troubel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /troubels/1
  # DELETE /troubels/1.json
  def destroy
    @troubel.destroy
    respond_to do |format|
      format.html { redirect_to troubels_url, notice: 'Permasalahan berhasil di hapus' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_troubel
      @troubel = Troubel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def troubel_params
      params.fetch(:troubel).permit(:name, :grade, :price)
    end
end

app/helpers/troubels_helper.rb
module TroubelsHelper
end

app/views/troubels/_form.html.erb
<div class="container">
   <div class="row">
      <div class="col-md-12 col-sm-12">
         <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
            <h1>Form Permasalahan</h1>
            <div class="panel panel-default">
            <!-- Default panel contents -->
               <div class="panel-body">

                  <div class="col-md-9 col-sm-9">

                     <%= form_for(@troubel) do |s| %>
                     <div class="form-group">
                        <%= s.label :Nama, class: "control-label"%>
                        <%= s.text_field :name, class: "form-control" %>
                     </div>

                     <div class="form-group">
                        <%= s.label :Tingkat_Kesulitan, class: "control-label"%>
                        <%= s.text_field :grade, class: "form-control" %>
                     </div>
                     <div class="form-group">
                        <%= s.label :Harga, class: "control-label"%>
                        <%= s.text_field :price, class: "form-control" %>
                     </div>
                        <%= s.submit "Simpan", class: "btn btn-default btn-lg" %>
                     <% end %>
                  </div>
               </div>
            </div>
         </div><!-- col-md-12 -->
      </div>
   </div>
</div>

app/views/troubels/index.html.erb
<div class="container">
   <div class="row">
      <div class="col-md-12 col-sm-12">
         <h1>Daftar Permasalah Servis</h1>
         <table class="table table-bordered">
           <thead>
              <tr>
                 <th>
                    <%= link_to new_troubel_path, class: "btn btn-default" do %>
                    <i class="glyphicon glyphicon-pencil"></i> Tambah Permasalahan
                    <% end %>
                 </th>
              </tr>
             <tr>
               <th>Nama</th>
               <th>Tingkat Kesulitan</th>
               <th>Harga</th>
               <th colspan="3"></th>
             </tr>
           </thead>

           <tbody>
             <% @troubels.each do |t| %>
               <tr>
                  <td><%= t.name %></td>
                  <td><%= t.grade %></td>
                  <td><%= t.price %></td>
                  <td><%= link_to edit_troubel_path(t), class: "btn btn-default" do%>
                     <i class="glyphicon glyphicon-cog"></i> Ubah
                     <% end %>
                  </td>
                  <td>
                     <%= button_to troubel_path(t), method: :delete, data: { confirm: 'Apakah anda yakin ingin menghapus ini?' }, class: "btn btn-danger" do %>
                     <i class="glyphicon glyphicon-trash"></i> Hapus
                    <% end %>
                  </td>
               </tr>
             <% end %>
           </tbody>
         </table>
      </div>
   </div>
</div>