config/routes.rb
Rails.application.routes.draw do

   root 'stoks#index'

      devise_for :users, controllers: { sessions: 'users/sessions' }
      resources :roles, only: [:index, :new, :create, :destroy]
      resources :activities
      resources :stoks
      resources :kategoris
      resources :orders, only: [:index, :show, :destroy]
      resource :cart, only: [:show]
      resources :order_items, only: [:index, :create, :update, :destroy]
      resources :clients
      resources :troubels, except: [:show]
      resources :services
      resources :kategoris do
         resources :stoks
      end

      get 'check_outs' => 'order_items#final_order', as: :check_out_route
      get 'set_nil/:id' => 'stoks#set_nil', as: :set_nil

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
   <div class="row">
      <div class="table-responsive">
         <table class="table table-condensed table-resposive">
            <tbody>
               <td class="col-md-1 col-sm-1"> <%= image_tag stok.gambar_url(:thumb) %> </td>
               <td class="col-md-5 col-sm-5">
                  <h4><%= stok.nama %></h4>
                  <h4>Harga Satuan: <span style="color: #e60000;">Rp <%= number_with_delimiter(order_item.unit_price, :delimiter => '.') %></span></h4>
               </td>
               <td class="col-md-6 col-sm-6">
                        <div class="row">
                           <%= form_for order_item, remote: true do |f| %>
                           <div class="col-md-6 col-sm-6">
                              <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
                              <%= f.hidden_field :stok_id, value: stok.id %>
                           </div>
                           <div class="col-md-6 col-sm-6">
                                 <%= f.submit "Perbarui Jumlah", class: "btn btn-default" %>
                                 <%= link_to "Hapus", order_item, data: { confirm: "Apakah anda yakin akan menghapus'#{order_item.stok.nama}' dari keranjang?"}, method: :delete, remote: true, class: "btn btn-danger" %>
                           </div>
                           <% end %>
                        </div>
                        <h4 >Total Harga: <span style="color: #e60000;"><%= number_with_delimiter(order_item.total_price, :delimiter => '.') %></span></h4>
               </td>
            </tbody>
         </table>
      </div>
   </div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
   <div class="alert alert-danger">
      <ul>
         <% @order_item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
      </ul>
   </div>
<% end %>

<% if @order_items.size == 0 %>

   <div class="text-center">
      <h4>Anda tidak mempunyai produk yang di tambahkan ke keranjang.</h4><br/>
      <%= button_to stoks_path(@stok),method: :get, class: "btn btn-lg btn-danger" do %>
         <i class="glyphicon glyphicon-shopping-cart"></i> Belanja Sekarang
         <% end %>
   </div>
<% else %>
   <div class="container">
      <% @order_items.each do |order_item| %>
         <%= render 'carts/cart_row', stok: order_item.stok, order_item: order_item, show_total: true %>
      <% end %>
      <%= button_to "Selesaikan Transaksi", check_out_route_path, method: :get, class: "btn btn-lg btn-success pull-left"%>

         <%= button_to stoks_path(@stok),method: :get, class: "btn btn-lg btn-danger pull-right" do %>
            <i class="glyphicon glyphicon-shopping-cart"></i> Belanja Lagi
            <% end %>

   </div>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>