config/routes.rb
Rails.application.routes.draw do

   root 'stoks#index'

      devise_for :users, controllers: { sessions: 'users/sessions' }
      resources :roles, only: [:index, :new, :create, :destroy]
      resources :activities
      resources :stoks
      resources :kategoris
      resources :orders, only: [:index, :show, :destroy]
      resource :cart, only: [:show]
      resources :order_items, only: [:index, :create, :update, :destroy]
      resources :clients
      resources :troubels, except: [:show]
      resources :services
      resources :kategoris do
         resources :stoks
      end

      get 'check_outs' => 'order_items#final_order', as: :check_out_route
      get 'set_nil/:id' => 'stoks#set_nil', as: :set_nil

end

app/models/kategori.rb
class Kategori < ActiveRecord::Base
	#aktifitas
	include PublicActivity::Model
	tracked owner: ->(controller, model) { controller && controller.current_user}
	#relasi database
	has_many :stoks, dependent: :destroy
	#uploader
	mount_uploader :gambar, AvatarUploader
	#validasi
	validates_presence_of :nama, :deskripsi, :message => "tidak boleh di kosongkan!"
	validates_uniqueness_of :nama, :message => "nama tidak boleh sama"
	validates_length_of :nama, :maximum => 22, :message => "nama harus kurang dari 23 karakter"

end

app/controllers/kategoris_controller.rb
class KategorisController < ApplicationController
   before_action :set_kategori, only: [:show, :edit, :update, :destroy]
   before_filter :authenticate_user!
   load_and_authorize_resource


  # GET /kategoris
  # GET /kategoris.json
  def index
    @kategoris = Kategori.all.order ("nama asc")
  end

  # GET /kategoris/1
  # GET /kategoris/1.json
  def show
    @stoks = @kategori.stoks.page(params[:page]).per(8)
  end

  # GET /kategoris/new
  def new
    @kategori = Kategori.new
    @stoks = @kategori.stoks
  end

  # GET /kategoris/1/edit
  def edit
  end

  # POST /kategoris
  # POST /kategoris.json
  def create
    @kategori = Kategori.new(kategori_params)
    @stoks = @kategori.stoks
    respond_to do |format|
      if @kategori.save
        format.html { redirect_to '/kategoris', flash: { success: "Kategori #{@kategori.nama} berhasil di buat." } }
        format.json { render :show, status: :created, location: @kategori }
      else
        format.html { render :new }
        format.json { render json: @kategori.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kategoris/1
  # PATCH/PUT /kategoris/1.json
  def update
    respond_to do |format|
      if @kategori.update(kategori_params)
        format.html { redirect_to '/kategoris', flash: { success: "Kategori #{@kategori.nama} berhasil di perbarui." } }
        format.json { render :show, status: :ok, location: @kategori }
      else
        format.html { render :edit }
        format.json { render json: @kategori.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kategoris/1
  # DELETE /kategoris/1.json

  def destroy
    @kategori.destroy
    respond_to do |format|
      format.html { redirect_to kategoris_url, notice: "Kategori #{@kategori.nama} berhasil di hapus." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kategori
      @kategori = Kategori.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kategori_params
      params.require(:kategori).permit(:gambar, :nama, :deskripsi)
    end
end

app/helpers/kategoris_helper.rb
module KategorisHelper
end

app/views/kategoris/_form.html.erb
<!-- form -->
<div class="container">
   <div class="row">
      <div class="col-md-12 col-sm-12">
         <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
            <h1>Form Kategori</h1>
            <div class="panel panel-default">
             <!-- Default panel contents -->
               <div class="panel-body">
                  <div class="col-md-8">
                     <%= render 'shared/error_messages', :object => @kategori %>
                     <div class="thumbnail thumbnail-form">
                        <%= image_tag @kategori.gambar_url(:thumb), id: "image-preview" %>
                     </div>
                     <%= form_for(@kategori) do |k| %>
                     <!-- error explanation-->
                     <div class="form-group">
                        <%= k.label :gambar, class: "control-label"%>
                        <%= k.hidden_field :gambar_cache %>
                        <%= k.file_field :gambar, id: "image-source", onchange: "previewImage();" %>
                     </div>
                     <div class="form-group">
                        <%= k.label :nama, class: "control-label"%>
                        <%= k.text_field :nama, class: "form-control" %>
                     </div>
                     <div class="form-group">
                        <%= k.label :deskripsi, class: "control-label"%>
                        <%= k.text_area :deskripsi, size: "25x10", class: "form-control" %>
                     </div>
                        <%= k.submit "Simpan", class: "btn btn-default btn-lg" %>
                     <% end %>
                  </div>
               </div>
            </div>
         </div><!-- col-md-12 -->
      </div>
   </div>
</div>

app/views/kategoris/edit.html.erb
<%= render 'form' %>

app/views/kategoris/index.html.erb
<div class="container">
   <div class="row">
      <% if @kategoris.size == 0 %>
         <p class="text-center">
            Tidak ada kategori yang tersedia untuk saat ini
            <strong><%= link_to "Tambah Kategori", new_kategori_path(@kategori)%></strong>
        </p>
      <% else %>
            <div class="col-md-12 col-sm-12">
               <div class="panel panel-default">
                  <div class="panel-body">
                     <% @kategoris.each do |k| %>
                     <div class="col-md-3 col-sm-3 text-center">
                        <table class="table table-bordered">
                           <tbody>
                              <tr style="height:75px;">
                                 <td>
                                    <%= link_to (image_tag k.gambar_url(:thumb)), kategori_path(k) %>
                                 </td>
                              </tr>
                              <tr>
                                 <td>
                                    <%= link_to (k.nama), kategori_path(k) %>
                                 </td>
                              </tr>
                           </tbody>
                        </table>
                     </div>
                     <% end %>
                  </div>
               </div>
            </div>
      <% end %>
   </div>
</div>

app/views/kategoris/new.html.erb
<%= render 'form'%>

app/views/kategoris/show.html.erb
<% if @kategori.stoks.size == 0 %>
		<p class="text-center">
			<i>produk untuk kategori <%= @kategori.nama %> tidak tersedia untuk saat ini</i>
			<strong><%= link_to 'Tambah Stok',new_kategori_stok_path(@kategori) %></strong>
		</p>
<% else %>
	<div class="jumbotron">
		<h1>
			<%= @kategori.nama %>
		</h1>
		<% if can? :update?, Kategori %>
			<div class="btn-group">
				<%= button_to edit_kategori_path(@kategori),method: :get, class: "btn btn-default" do %>
					<i class="glyphicon glyphicon-wrench"></i> Ubah
					<% end %><br>
				<%= button_to @kategoris,method: :delete, data: {confirm: "Apakah anda yakin akan menghapus produk #{@kategori.nama} ?"}, class: "btn btn-danger" do %>
					<i class="glyphicon glyphicon-trash"></i> Hapus
					<% end %>
			</div>
		<% end %>
		<p><small><%= @kategori.deskripsi %></small> </p>
	</div>
	<div class="navbar navbar-default">
		<ul class="nav nav-tabs">
			<li role="presentation" class="active"><a href="#">Lihat Stok <%= "#{@kategori.nama}" %></a></li>
			<li role="presentation"><%= link_to 'Tambah Stok',new_kategori_stok_path(@kategori) %></li>
		</ul>
	</div>
<!-- panel stok -->
	<div class="container">
		<div class="col-md-12 col-sm-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Daftar stok <%= @kategori.nama %>
				</div>
				<div class="panel-body">
						<% @stoks.each do |s| %>
						<div class="col-md-3 col-sm-3 col-xs-3">
							<div class="thumbnail thumbnail-link">
								<%= link_to (image_tag s.gambar_url(:normal)),stok_path(s) %>
								<div class="caption">
									<h3>Rp <%= number_with_delimiter(s.harga_jual, :delimiter => '.' )  %></h3>
									<p><%= s.nama.truncate_words(7) %></p>
								</div>
							</div>
						</div>
						<% end %>
				</div>
			</div>
			<!--navigasi halaman -->
			<nav class="pagination pull-right">
	    		<ul class="pagination-xs">
	    			<nav aria-label="...">
	      			<ul class="pager">
	        				<li><%= link_to_previous_page (@stoks),'Sebelumnya' %></li>
	        				<li><%= link_to_next_page (@stoks),'Selanjutnya' %></li>
	      			</ul>
	    			</nav>
	    		</ul>
	  		</nav>
		</div>
	</div>
<% end %>